# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:title

# Setup
title:            Luís Ramalho
tagline:          'Entrepreneur & Developer'
description:      '"Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time." — Thomas Edison.'
url:              http://luisramalho.com

author:
  name:           'Luís Ramalho'
  url:            https://twitter.com/luisramalho

paginate:         3
