# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:            Luís Ramalho
tagline:          'Entrepreneur & Developer'
description:      '"Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time." — Thomas Edison.'

author:
  name:           'Luís Ramalho'
  url:            https://twitter.com/luisramalho

paginate:         3

gems:
  - jekyll-sitemap
